/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s
and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
class Solution
{
public:
   char findTheDifference(string s, string t)
   {
       string tmp = t;
       for (auto c : s)
       {
           auto pos = tmp.find_first_of(c);
           assert(pos != string::npos);
           tmp.erase(pos, 1);
       }

       return tmp[0];
   }
};
